accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("signin/", views.SignIn, name="signin"),
    path("signup/", views.SingUp, name="signup"),
    path("logout/", views.logoutpage, name="logout"),
]

community/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("home/grup/<int:grup_id>/", views.gruphome, name='grup'),
]

example/urls.py
# example/urls.py
from django.urls import path

from example.views import index


urlpatterns = [
    path('', index),
]

vercel_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("community.urls")),
    path("accounts/", include("accounts.urls")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Users(AbstractUser):
    gender_cho = [("MAN","MAN"),("WOMAN","WOMAN")]
    gender = models.CharField(max_length=6, choices=gender_cho)
    
    def __str__(self):
        return self.username

community/models.py
from django.db import models
from accounts.models import Users
from django.utils import timezone
# Create your models here.

class Group(models.Model):
    owner = models.OneToOneField(Users, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    createdfrom = models.DateField(auto_created=True, default=timezone.now)
    members = models.ManyToManyField(Users, through='GroupMember', related_name='group_memberships')
    def __str__(self):
        return self.name

class GroupMember(models.Model):
    status_cho = [("Members","Members"),("Admin","admin")]
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    member = models.ForeignKey(Users, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=status_cho)
    joins = models.DateField(auto_created=True, default=timezone.now)
    class Meta:
        unique_together = ('group', 'member')
    def __str__(self):
        return (f"group: {self.group} | member: {self.member}")
    
class PesanGrup(models.Model):
    pengirim = models.ForeignKey(Users, on_delete=models.CASCADE)
    grup = models.ForeignKey(Group,on_delete=models.CASCADE)
    text_pesan = models.TextField(null=False)
    kirim = models.DateTimeField(null=False, auto_now_add=True)
    def __str__(self):
        return (f"{self.pengirim} || {self.grup}")

accounts/forms.py
from django import forms
from .models import Users
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

class SignInForms(AuthenticationForm):
    class Meta:
        model = Users
        fields = ["username", "password"]
    
class SignUpForms(UserCreationForm):
    gender_cho = [("MAN","MAN"),("WOMAN","WOMAN")]
    gender = forms.ChoiceField(choices=gender_cho)
    class Meta:
        model = Users
        fields = ["username", "email", "password1", "password2", "gender"]

community/forms.py
from django import forms
from .models import PesanGrup

class PesanGrupForm(forms.ModelForm):
    class Meta:
        model = PesanGrup
        fields = ["text_pesan"]

accounts/views.py
from django.shortcuts import render, redirect
from .forms import SignInForms, SignUpForms
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Users

# Create your views here.

def SignIn(request):
    if request.method == "POST":
        form = SignInForms(data=request.POST)
        if form.is_valid():
            users = form.get_user()
            login(request, users)
            return redirect("home")
    else:
        form = SignInForms()
    return render(request, "signin.html", {"form":form})

def SingUp(request):
    if request.method == "POST":
        form = SignUpForms(request.POST)
        if form.is_valid():
            form.save()
            return redirect("signin")
    else:
        form = SignUpForms()
    return render(request, "signup.html", {"form":form})

def logoutpage(request):
    logout(request)
    return redirect("signin")

community/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import GroupMember,PesanGrup, Group
from django.urls import reverse
from .forms import PesanGrupForm
# Create your views here.

@login_required
def home(request):
    user = request.user
    grm = GroupMember.objects.filter(member=user)
    kosong = "Silahkan Pilih Grup"
    rumah = {"user":user,
             "grm":grm,
             "kosong":kosong}
    
    return render(request, "home.html", rumah)

def gruphome(request, grup_id):
    user = request.user
    group = get_object_or_404(Group, pk=grup_id)
    grm = GroupMember.objects.filter(member=user)
    pesanya =  PesanGrup.objects.filter(grup_id=group) 
    #form Buat PESAN
    if request.method == "POST":
        form = PesanGrupForm(request.POST)
        if form.is_valid():
            pesan_grup = form.save(commit=False)
            pesan_grup.pengirim = user
            pesan_grup.grup_id = group.id
            pesan_grup.save()  # Simpan objek pesan_grup ke database
    else:
        form = PesanGrupForm()
    try:
        home = {"grm":grm,
                "pesanya":pesanya,
                "form":form}
    except:
        pass
    return render(request, "home.html", home)

example/views.py
# example/views.py
from datetime import datetime

from django.http import HttpResponse

def index(request):
    now = datetime.now()
    html = f'''
    <html>
        <body>
            <h1>Hello from Vercel!</h1>
            <p>The current time is { now }.</p>
        </body>
    </html>
    '''
    return HttpResponse(html)

accounts/templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/signin.css' %}">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Community Hub</title>
</head>
<body>
  <header class="header">
    <h1 class="community">Community</h1>
    <div class="wrapped-search">
      <input class="search-input" type="text" placeholder="Cari...">
      <button class="search-button">Cari</button>
    </div>
  </header>
  <div class="container">
    <div class="left-side">
      <p>CONNECTING</p>
      <p>WITH</p>
      <p>EVERYONE</p>
    </div>
    <div class="right-side">
      <form method="post">
        {% csrf_token %}
        <p>
          <label for="id_username"></label>
          <input class="box" type="text" name="username" autofocus
            placeholder="Username" autocapitalize="none"
            autocomplete="username" maxlength="150" required
            id="id_username">
        </p>
        <p>
          <label for="id_password"></label>
          <input class="box" type="password" name="password"
            autocomplete="current-password" required
            id="id_password" placeholder="Password">
        </p>
        <button type="submit" class="login-button">SIGN IN</button>
        <a href="#" class="forgot-pwd">forgot password? </a>
      </form>
      <p class="signup">No have account? <a href="{% url 'signup' %}">Sign Up</a></p>
    </div>
  </div>
  <footer class="footer">
    <div class="footer-links">
      <a href="#">Tentang</a>
      <a href="#">Masuk</a>
      <a href="#">Daftar</a>
      <a href="#">Panduan Komunitas</a>
      <a href="#">Iklan</a>
      <a href="#">Kerja Sama</a>
      <a href="#">Kebijakan Privasi</a>
    </div>
    <p>&copy; 2023 Community Hub</p>
  </footer>
</body>
</html>

accounts/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/signup.css' %}">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Community Hub - Sign Up</title>
</head>
<body>
  <header class="header">
    <h1 class="community">Community</h1>
    <div class="wrapped-search">
      <input class="search-input" type="text" placeholder="Cari...">
      <button class="search-button">Cari</button>
    </div>
  </header>
  <div class="container">
    <div class="left-side">
      <p class="kiri">CONNECTING</p>
      <p class="kiri">WITH</p>
      <p class="kiri">EVERYONE</p>
    </div>
    <div class="right-side">
      <form method="post">
        {% csrf_token %}
        <p>
          <label for="id_username"></label>
          <input type="text" name="username" class="box" maxlength="150" placeholder="Username" autofocus required id="id_username">
        </p>
        <p>
          <label for="id_email"></label>
          <input type="email" placeholder="Email" class="box" name="email" maxlength="254" id="id_email">
        </p>
        <p>
          <label for="id_password1"></label>
          <input type="password" placeholder="Password" class="box" name="password1" autocomplete="new-password" required id="id_password1">
        </p>
        <p>
          <label for="id_password2"></label>
          <input type="password" placeholder="Confirm Password" class="box" name="password2" autocomplete="new-password" required id="id_password2">
        </p>
        <p>
          <label for="id_gender"></label>
          <select name="gender" id="id_gender" class="box-selected">
            <option value="" disabled selected>Select Gender</option>
            <option value="MAN">MAN</option>
            <option value="WOMAN">WOMAN</option>
          </select>
        </p>
        <button type="submit">SIGN UP</button>
      </form>
      <p class="login">Already have an account? <a href="{% url 'signin' %}">Log In</a></p>
    </div>
  </div>
  <footer class="footer">
    <div class="footer-links">
      <a href="#">Tentang</a>
      <a href="#">Masuk</a>
      <a href="#">Daftar</a>
      <a href="#">Panduan Komunitas</a>
      <a href="#">Iklan</a>
      <a href="#">Kerja Sama</a>
      <a href="#">Kebijakan Privasi</a>
    </div>
    <p class="wm">&copy; 2023 Community Hub</p>
  </footer>
</body>
</html>

community/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home Community</title>
  {% load static %}
  <link rel="shortcut icon" href="{% static 'img/fav.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
  <header class="header">
    <a href="{% url 'home' %}">
      <h1 class="community">Community</h1>
    </a>
    <div class="wrapped-search">
      <input class="search-input" type="text" placeholder="Cari...">
      <button class="search-button">Cari</button>
      <a href="{% url 'logout' %}">
        <button>logout</button>
      </a>
    </div>
  </header>
  <div class="container">
    <div id="box1" class="box" onclick="toggleBox2()">
      <button id="toggleButton" class="toggle-button">
        <img class="arrow-image" src="{% static 'img/kiri.png' %}">
      </button>
    </div>
    <div id="box2" class="box custom-scrollbar">
      <ul>
        <div class="pmorcom"></div>
        <div class="head-box2">
          <div class="message-box"></div>
          <div class="group-box"></div>
          <div class="create"></div>
        </div>
        {% for grms in grm %}
        <div class="box-commun">
          <li>
            <a href="{% url 'grup' grup_id=grms.group.id %}">
              <p class="nama-gr"><b>{{ grms.group }}</b></p>
            </a>
            <p class="status-gr">{{ grms.status }}</p>
            <div class="iconpesan"></div>
            <div class="iconpost"></div>
            <div class="icongr"></div>
          </li>
        </div>
        {% endfor %}          
        <div class="end-loop"></div>
      </ul>
    </div>
    <div id="box3" class="box">
      {% if request.path == '/' %}
      <h1>SILAHKAN PILIH GROUP</h1>
      {% endif %}
      <ul>
        {% for pesan in pesanya %}
        {% if pesan.pengirim == request.user %}
        <li>
          <div class="pesankanan">
            <p class="pengirim">{{ pesan.pengirim }}</p>
            <p class="text-pesan">{{ pesan.text_pesan }}</p>
            <p class="tanggal">{{ pesan.kirim|time:"H:i:s" }}</p>
          </div>
        </li>
        {% else %}
        <li>
          <div class="pesankiri">
            <p class="pengirim">{{ pesan.pengirim }}</p>
            <p class="text-pesan">{{ pesan.text_pesan }}</p>
            <p class="tanggal">{{ pesan.kirim|time:"H:i:s" }}</p>
          </div>
        </li>
        {% endif %} 
        {% endfor %}
        {% if request.resolver_match.url_name == 'grup' %}
        <form method="post">
          {% csrf_token %}
          <label for="id_text_pesan"></label>
            <textarea name="text_pesan" cols="40" rows="10" required id="id_text_pesan">
            </textarea>
          <button>enter</button>
        </form>
        {% endif %}
        <div class="endloop2"></div>
      </ul>
    </div> 
  </div>
  <script>let box2Open = false;
    const toggleButton = document.getElementById("toggleButton");
    const arrowImage = document.querySelector(".arrow-image");
    
    function toggleBox2() {
      const box2 = document.getElementById("box2");
    
      if (!box2Open) {
        box2.style.flex = "0 0 400px";
        arrowImage.src = "{% static 'img/kanan.png' %}";
      } else {
        box2.style.width = "0";
        box2.style.flex = 0;
        arrowImage.src = "{% static 'img/kiri.png' %}";
      }
      box2Open = !box2Open;
    }
    function openBox2() {
      if (box2Open) {
        toggleBox2();
      }
    }
    </script>
</body>
</html>